### ISSUE TITLE
Export to csv/json/odf is broken

### ISSUE THREAD

**Issue by PossiblyPeso** [CubeLabsNZ/CubeTime#215]
**Describe the bug**
Exporting sessions in any format leads to the solves being jumbled in order. 

**To Reproduce**
Steps to reproduce behaviour:
Export any session, then examine the dates of the files. 

**Expected behavior**
Solves should be in order so that averages are correct. 

**Screenshots or screen recordings**

**Crash log if applicable**

**Smartphone (please complete the following information):**
 - Device: iPhone 12 Pro
 - OS: iOS 17.4.1
 - App version 3.0.0
![IMG_5552](https://github.com/CubeStuffs/CubeTime/assets/127100536/651d4572-aafc-40bd-bb94-9655bd97e902)

**Additional context**

**Comment by pdtxie** [comment]
referring @xbjfk to this issue. thanks for bringing this to our attention

**Comment by pdtxie** [comment]
Hi, we are reviewing this issue. We've decided this isn't too much of a problem as the export is intended as a data dump for you to use. You can sort and filter in tools like Excel. Thanks
