### ISSUE TITLE
Easier access to "Tools"

### ISSUE THREAD

**Issue by mbtools** [CubeLabsNZ/CubeTime#217]
Love the app! 

The tools are "hidden" in "Sessions", not where one would expect them.

How about moving them to the main toolbar?

![image](https://github.com/CubeStuffs/CubeTime/assets/59966492/04309541-2831-4d2f-89de-69f71137ad05)

**Comment by pdtxie** [comment]
thanks for this suggestion! we'll discuss internally on this design choice

**Comment by xbjfk** [comment]
sorry, i dont think we'll change it to the tab bar - it will make for an inconsistent experience on devices where there is no room - such as the iphone se. we are open to other ideas in future but couldn't think of any
