### ISSUE TITLE
Customize date format 

### ISSUE THREAD

**Issue by vicjang** [CubeLabsNZ/CubeTime#227]
The date displayed in each record is displayed as DD/MM/YY at the moment. 

As far as I know there’s no way to change this?
I know many including myself would appreciate the option to change the date format, for example MM/DD/YYYY, MM/DD/YY, YYYY/MM/DD etc.

If this feature already exists, please kindly provide instruction on where to find it. Thank you!

**Comment by pdtxie** [comment]
changed date format to system format
