### ISSUE TITLE
Prompting before deleting a time

### ISSUE THREAD

**Issue by jmlumpkin** [CubeLabsNZ/CubeTime#231]
**Is your feature request related to a problem? Please describe if applicable.**
While you may want to often delete times rather quickly, it can also be frustrating as it can adjust your averages or recordings, if you inadvertently  delete a time. It would be nice to have a prompt here first before the delete. This could be a configurable option too, as in let the user say that they want to be prompted or not. 

**Describe the solution you'd like**
I would like to see a common alert pop up confirming that yes, I do want to delete a time. 

**Additional context**
I am actually working on some code to implement this. So far I have added it to the TimeDetail.

**Comment by jmlumpkin** [comment]
Ive added this to the three places I noticed you were able to delete a time. I plan on next adding an option so that under settings one can determine if they want this on or not (and probably defaulting to off, since its what is there now)

**Comment by jmlumpkin** [comment]
Just created pull request #235. Thanks for letting me try this out!

**Comment by pdtxie** [comment]
Merged, thanks!
